name: helper-cool

services:
  helper-cool:
    container_name: helper-cool
    image: registry.cn-beijing.aliyuncs.com/daodao-bot/helper-cool:latest
    pull_policy: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
        reservations:
          cpus: "0.05"
          memory: "64M"
    #ports:
    #  - "${SERVER_PORT}:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Shanghai
      DT: "2025-01-01T00:00:00"
    env_file:
      - .env
    networks:
      - common
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

networks:
  common:
    external: true
