version: '1.0'
name: docker-build
displayName: docker-build
triggers:
  trigger: auto
  push:
    tags:
      prefix:
        - t-
    paths:
      include:
        - ^.*$
variables:
  NAMESPACE: daodao-bot
  APPLICATION: helper-web
stages:
  - name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 构建镜像
        type: cert
        certificate: aliyun-cr-daodao-bot
        tag: ${NAMESPACE}/${APPLICATION}:${GITEE_BRANCH}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
      - step: build@docker
        name: docker_build
        displayName: 镜像构建
        type: cert
        certificate: aliyun-cr-daodao-bot
        tag: ${NAMESPACE}/${APPLICATION}:latest
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
